export const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME || "Ecommerce Demo"
export const APP_SLOGAN =
    process.env.NEXT_PUBLIC_APP_SLOGAN || "BEST E-COMMERCE WEBSITE"
export const APP_DESCRIPTION =
    process.env.NEXT_PUBLIC_APP_DESCRIPTION || "IT IS INSPIRED BY AMAZON.COM, CREATED BY NEXT JS & MONGODB"